### ISSUE TITLE
I am so sorry!!!!!!

### ISSUE THREAD

**Issue by sugar1pct** [Git-Stuco/HW2#2]
I did not use the -f option, but after I git push, everything disappears here!!!
I am REALLY SORRY!!! 
What should I do???

**Comment by sugar1pct** [comment]
Though I was able to restore everything back in place... but every file has a duplicate now... I think I'd better just leave them like that, instead of massing them up even more... I am really sorry....

**Comment by Dogfalo** [comment]
Don't worry about it. We are all here to learn :)
