### ISSUE TITLE
Permission Denied and 403 error

### ISSUE THREAD

**Issue by xiaoxiao26-zz** [Git-Stuco/HW2#3]
This is already a closed issue, but I am having the same error. When I try pushing, it says permission to this remote repository is denied to me.

**Comment by Dogfalo** [comment]
Did you join the group invitation?

On Tue, Jan 27, 2015 at 4:49 PM, xiaoxiao26 notifications@github.com
wrote:

> This is already a closed issue, but I am having the same error. When I try
> pushing, it says permission to this remote repository is denied to me.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Git-Stuco/HW2/issues/3.

## 

Doggy sends his greetings from Mars.

**Comment by xiaoxiao26-zz** [comment]
Nope, that must be it. I don't recall ever receiving it either, could you send the invitation to me again?

**Comment by Dogfalo** [comment]
I reset it

**Comment by xiaoxiao26-zz** [comment]
Did you mean resent or reset? I didn't receive a group invitation, and I still can't push to the repository.

**Comment by Dogfalo** [comment]
Check your email

**Comment by xiaoxiao26-zz** [comment]
I was checking the wrong email... Thanks for the help!
